// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'App': string;
  'App-logo-spin': string;
  'AppHeader': string;
  'AppLink': string;
  'AppLogo': string;
}
declare var cssExports: CssExports;
export = cssExports;
